kind: pipeline
name: default

clone:
  depth: 5

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --remote

steps:
- name: test
  image: haskell:8.6
  commands:
  - stack --no-terminal --install-ghc test --bench --only-dependencies
  - stack --no-terminal test --bench --no-run-benchmarks --no-haddock-deps --pedantic
