kind: pipeline
name: default

clone:
  depth: 5

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --init

- name: restore
  image: homerovalle/drone-gcs-cache
  settings:
    pull: true
    bucket: matsubara-drone-cache
    json_key:
      from_secret: gcs-access-json-key
    restore: true

- name: test
  image: haskell:8.6
  commands:
  - stack --no-terminal --stack-root `pwd`/.stack --install-ghc test --bench --only-dependencies
  - stack --no-terminal --stack-root `pwd`/.stack test --bench --no-run-benchmarks --no-haddock-deps --pedantic

- name: rebuild
  image: homerovalle/drone-gcs-cache
  settings:
    pull: true
    bucket: matsubara-drone-cache
    json_key:
      from_secret: gcs-access-json-key
    rebuild: true
    mount:
      - .stack/
      - .stack-work
    when:
      event: push

- name: flush
  image: homerovalle/drone-gcs-cache
  settings:
    pull: true
    bucket: matsubara-drone-cache
    json_key:
      from_secret: gcs-access-json-key
    flush: true
    flush_age: 14
