name:                drone
version:             1.0.1
github:              "matsubara0507/drone-haskell"
license:             MIT
author:              "MATSUBARA Nobutada"
maintainer:          "t12307043@gunma-u.ac.jp"
copyright:           "2018 MATSUBARA Nobutada"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/matsubara0507/drone-haskell#readme>

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers >= 0.5.4
- extensible >= 0.6
- formatting >= 6.3.0
- microlens
- req >= 1.0.0
- text

library:
  source-dirs: src

tests:
  drone-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - drone
    - hspec
    - servant-server
    - warp
    - aeson
    - req >= 2.0.0
